# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20160711_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightinginfo',
            name='body_de',
            field=models.TextField(blank=True, verbose_name='Weitere Erklärung_de'),
        ),
        migrations.AlterField(
            model_name='sightinginfo',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Further explanation_en'),
        ),
    ]
