# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-04 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_sightinginfo_imagecover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertcomment',
            name='body',
            field=models.CharField(max_length=1024, verbose_name='Comentario'),
        ),
    ]
