# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160708_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value_ca',
            field=models.CharField(default='', max_length=128, verbose_name='Resposta_ca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='value_de',
            field=models.CharField(blank=True, max_length=128, verbose_name='Antwort_de'),
        ),
        migrations.AddField(
            model_name='answer',
            name='value_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Answer_en'),
        ),
        migrations.AddField(
            model_name='location',
            name='name_ca',
            field=models.CharField(default='', max_length=128, verbose_name='Nom_ca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='name_de',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name_de'),
        ),
        migrations.AddField(
            model_name='location',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name_en'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_ca',
            field=models.CharField(default='', max_length=128, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='name_de',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name_de'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name_en'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ca',
            field=models.CharField(default='', max_length=128, verbose_name='Títol_ca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title_de',
            field=models.CharField(blank=True, max_length=128, verbose_name='Titel_de'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Title_en'),
        ),
        migrations.AddField(
            model_name='sightinginfo',
            name='body_ca',
            field=models.TextField(default='', verbose_name='Explicació més detallada_ca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sightinginfo',
            name='body_de',
            field=models.TextField(default='', verbose_name='Weitere Erklärung_de'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sightinginfo',
            name='body_en',
            field=models.TextField(default='', verbose_name='Further explanation_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sightinginfo',
            name='quickBody_ca',
            field=models.TextField(default='Clic per a més informació', max_length=128, verbose_name='Breu explicació_ca'),
        ),
        migrations.AddField(
            model_name='sightinginfo',
            name='quickBody_de',
            field=models.TextField(blank=True, default='Klicken Sie für weitere Informationen', max_length=128, verbose_name='Kurze Erklärung_de'),
        ),
        migrations.AddField(
            model_name='sightinginfo',
            name='quickBody_en',
            field=models.TextField(blank=True, default='Click for more information', max_length=128, verbose_name='Short explanation_en'),
        ),
        migrations.AddField(
            model_name='sightinginfo',
            name='title_ca',
            field=models.CharField(default='', max_length=128, verbose_name='Títol_ca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sightinginfo',
            name='title_de',
            field=models.CharField(blank=True, max_length=128, verbose_name='Titel_de'),
        ),
        migrations.AddField(
            model_name='sightinginfo',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Title_en'),
        ),
    ]
