# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20160721_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'verbose_name': 'Versión App Android', 'verbose_name_plural': 'Versiones App Android'},
        ),
    ]
