# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-15 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20170515_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='contact_phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Móvil de Contacto'),
        ),
    ]
